# Comments are provided throughout this file to help you get started.
# If you need more help, visit the Docker compose reference guide at
# https://docs.docker.com/go/compose-spec-reference/

# Here the instructions define your application as a service called "server".
# This service is built from the Dockerfile in the current directory.
# You can add other services your application may depend on here, such as a
# database or a cache. For examples, see the Awesome Compose repository:
# https://github.com/docker/awesome-compose
version: "3.9"

volumes:
  postgres_data:

services:
  postgres:
      image: postgres:latest
      restart: always
      hostname: postgres
      container_name: postgres
      environment:
        POSTGRES_DB: db
        POSTGRES_USER: user
        POSTGRES_PASSWORD: password
      ports:
        - "5432:5432"
      volumes:
        - ../database:/docker-entrypoint-initdb.d
        - postgres_data:/var/lib/postgresql/data
  nginx:
    image: nginx:latest
    hostname: nginx
    container_name: nginx
    platform: linux/amd64
    restart: always
    ports:
      - "80:80"
    volumes:
      - ../configs/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - server
    networks:
      - backend
  server:
    hostname: server
    env_file:
      - ../.env
    restart: always
    build:
      context: ..
      dockerfile: build/Dockerfile.server
    deploy:
      replicas: 3
    depends_on:
      - postgres
    networks:
      - backend
networks:
  backend: